* morse code
  Welcome to your javascript toolkit for morse code.

  These functions are built for and tested with Chrome on a
  Chromebook.  They may, possibly, work with other modern browsers or
  with Chrome in other host environments

  When fully implemented, this package will enable you to:

  * translate text into morse code and send the code as a keyed tone
  * read various keying events and translate them into a keyed tone
  * translate keyed tones into morse code and into text
  * implement a simple morse code training game ala simple simon
  * communicate over the internet with morse code WebRTC

* the chrome extension
  The chrome extension sources are kept in the extension directory
  which has its own README file to explain how the sources work.

  The demos can be run directly from [[http://rawgit.com/recri/morse-code/master/extension/index.html]].

* the keyer accessories
  Keying morse code on a computer keyboard using the ALT and CTRL keys
  is less than an optimal experience, I've built a few USB keyer
  accessories which improve the experience.  These are programs for
  the Teensy varieties of Arduino clones developed by http://pjrc.com/.

  The SwitchKeyer is a program written for the Teensy 2.0 processor.
  A mechanical key, either a straight key or iambic paddle, plugs into
  the SwitchKeyer and it generates the keyboard events for the Alt and
  Control keys over a USB Keyboard interface.  The Teensy processor
  and key jack fit into a mini Altoids tin.

  The TouchKeyer is a program written for the Teensy 3.1 processor.
  It uses a pair of touch sensitive paddles which generate the
  keyboard events for the Alt and Control keys over a USB Keyboard
  interface.  The Teensy processor is sandwiched between two pieces of
  perfboard which provide the substrate for the tocuch paddles.

  These should be merged into a single accessory which serves both
  purposes at some point, perhaps with additional functionality.
